rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y -1 -z 3.0599 -model point_1
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y -1 -z 4.0599 -model point_2
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y -1 -z 5.0599 -model point_3
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y 0 -z 3.0599 -model point_4
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y 0 -z 4.0599 -model point_5
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y 0 -z 5.0599 -model point_6
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y 1 -z 3.0599 -model point_7
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y 1 -z 4.0599 -model point_8
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x -1 -y 1 -z 5.0599 -model point_9
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 0 -y -1 -z 3.0599 -model point_10
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 0 -y -1 -z 5.0599 -model point_11
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 0 -y 0 -z 3.0599 -model point_12
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 0 -y 0 -z 5.0599 -model point_13
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 0 -y 1 -z 3.0599 -model point_14
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 0 -y 1 -z 5.0599 -model point_15
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y -1 -z 3.0599 -model point_16
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y -1 -z 4.0599 -model point_17
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y -1 -z 5.0599 -model point_18
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y 0 -z 3.0599 -model point_19
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y 0 -z 4.0599 -model point_20
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y 0 -z 5.0599 -model point_21
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y 1 -z 3.0599 -model point_22
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y 1 -z 4.0599 -model point_23
rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/files/vertices.urdf -urdf -x 1 -y 1 -z 5.0599 -model point_24